enyo.depends("$lib/layout", "$lib/onyx", "resources/js/jquery-1.8.3.min.js",
		"resources/js/cookie.js",
		"resources/js/jquery-ui-1.10.3.custom.min.js",
		"resources/js/jquery.layout-latest.min.js",
		"resources/js/bootstrap.min.js", "resources/js/bootbox.min.js",
		"resources/js/jquery.mCustomScrollbar.js",
		"resources/js/css-browser-selector.js", "resources/js/utility.js",
		"resources/js/jquery.timeago.js", "resources/js/layout.js",
		"resources/js/jquery.validate.js", "resources/js/jquery-tipsy.js",
		"resources/js/jquery.fileupload.js",
		"resources/js/jquery.iframe-transport.js", "resources/js/raphael.js",
		"resources/js/raphael.export.js",
		"resources/js/raphael.free_transform.js",
		"resources/js/raphael.json.js", "resources/js/colorpicker.js",
		"resources/js/atmosphere.js", "resources/js/blackbird.js",
		"resources/js/jquery.livequery.js",
		"resources/js/jquery.cssemoticons.min.js",
		"resources/js/jquery.carouFredSel-6.1.0-packed.js",
		"resources/js/handlebars.js", "resources/js/jquery.knob.js",
		"resources/js/store.min.js", "resources/js/sha256.js",
		"resources/js/enc-base64-min.js", "resources/js/core.js",
		"resources/js/wbRest.js", "resources/js/wboard-config.js",
		"resources/js/chatresource.js", "resources/js/wboard-drawing.js",
		"resources/js/whiteboard.js", "resources/js/opentok.min.js", "app.js")
