enyo.depends(
    "Exports.js",
	"entities/AccountManager.js",
	"entities/DeviceManager.js",
	"entities/UserDirectory.js",
	"entities/ApplicationManager.js",
	"HttpClient.js",
	"Runtime.js",
	"Util.js"
)