enyo.depends(
	"lib/whiteboard",
    "Exports.js",
	"entities/AccountManager.js",
	"entities/DeviceManager.js",
	"entities/UserDirectory.js",
	"entities/AssetManager.js",
	"entities/ApplicationManager.js",
	"entities/ConferenceManager.js",
	"entities/board/Page.js",
	"entities/board/Document.js",
	'Cookie.js',
	"HttpClient.js",
	"Runtime.js",
	"Util.js",
	"Analytics.js",
	"log.js"
)