enyo.depends(
	"lib/whiteboard",
    "Exports.js",
	"entities/AccountManager.js",
	"entities/DeviceManager.js",
	"entities/UserDirectory.js",
	"entities/ApplicationManager.js",
	"entities/board/Page.js",
	"HttpClient.js",
	"Runtime.js",
	"Util.js",
	"log.js"
)